name: Update Dependencies

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:


jobs:
    renovate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Self-Hosted Renovate
              uses: renovatebot/github-action@v40.0.2
              with:
                configurationFile: .github/renovate.json
                docker-user: root
                token: ${{ secrets.RENOVATE_TOKEN }}
              env:
                LOG_LEVEL: 'debug'